main: fr.gabrielmercier.skinchanger.SMain
name: SkinChanger
version: 1.0
author: Gabriel MERCIER
load: STARTUP
database: false
commands:
  s:
    permission: skinchanger.s.*
    permission-message: §cYou can't use this with actual permission. Please contact the administrator of the server.
    description: The main command of the plugin. Type /s for help.